import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import vm from 'node:vm'
const context = vm.createContext({})
vm.runInContext(readFileSync(new URL('../lib/History.js', import.meta.url), 'utf8').replace(/^\.pragma library\s*/m, ''), context)
const { aggregate, bucketAt, connected } = context
const samples = Array.from({ length: 1001 }, (_, t) => ({ t, cpuPct: t === 503 ? 99 : 1, conns: 0, latMs: null, rssKb: 42 }))
const view = aggregate(samples, 1000, 1000, 20)
assert.equal(view.count, 1001)
assert.equal(view.buckets.length, 20)
assert.equal(view.stats.cpuPct.hi, 99)
assert.equal(Math.max(...view.buckets.map(b => b.cpuPct.hi)), 99, 'a narrow spike survives aggregation')
assert.equal(view.first, 0)
assert.equal(view.last, 1000)
assert.equal(view.buckets[19].count, 51, 'inclusive end belongs to the final bucket')
assert.equal(view.stats.latMs.lo, null)
assert.equal(view.buckets[0].latMs.avg, null)
const sparse = aggregate([{ t: 0, cpuPct: 0 }, { t: 21, cpuPct: 8 }, { t: 22, cpuPct: null }, { t: 31, cpuPct: 9 }], 40, 40, 4)
assert.equal(bucketAt(sparse, 15), -1)
assert.equal(bucketAt(sparse, 21), 1)
assert.equal(connected(sparse.buckets[0], sparse.buckets[1], 'cpuPct'), false, 'empty bins break the average line')
assert.equal(connected(sparse.buckets[1], sparse.buckets[2], 'cpuPct'), false, 'null samples break surrounding average lines')
assert.equal(connected(view.buckets[0], view.buckets[1], 'cpuPct'), true)
const later = aggregate(samples, 100, 1000, 20)
assert.equal(later.count, 101)
assert.equal(later.stats.cpuPct.hi, 1, 'bounds describe the selected time window')
samples.push({ t: 1001, cpuPct: 100 })
assert.equal(view.count, 1001)
assert.notEqual(aggregate(samples, 1000, 1000, 20).buckets, view.buckets)
assert.equal(aggregate([], 3600, 1000).first, null)
assert.equal(aggregate([{t: 1000, cpuPct: 0}], 3600, 1000).stats.cpuPct.lo, 0)
assert.deepEqual(Array.from(context.ranges, r => r.label), ['30m', '1h', '3h', '6h', '1d', '2d'])
console.log('Time-window bounds, peak-preserving buckets, null gaps, inclusive endpoints and immutable views passed')
